// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbRLbQ1eueEZa2vqG1diOfV9PcNt8SR-s',
    appId: '1:1038391091623:web:bd2e84205c66b5edc65682',
    messagingSenderId: '1038391091623',
    projectId: 'bodyguard-d274c',
    authDomain: 'bodyguard-d274c.firebaseapp.com',
    databaseURL: 'https://bodyguard-d274c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bodyguard-d274c.appspot.com',
    measurementId: 'G-SSMHBM1D01',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG4npb2Uhsp7aUqycOJ6GdlD8UO5SG2k4',
    appId: '1:1038391091623:android:989bde83ac0f0035c65682',
    messagingSenderId: '1038391091623',
    projectId: 'bodyguard-d274c',
    databaseURL: 'https://bodyguard-d274c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bodyguard-d274c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBAi-yovpJsPD2jX7vLdKJEhb5pXNlG3Y',
    appId: '1:1038391091623:ios:384e585d3db478b6c65682',
    messagingSenderId: '1038391091623',
    projectId: 'bodyguard-d274c',
    databaseURL: 'https://bodyguard-d274c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bodyguard-d274c.appspot.com',
    iosBundleId: 'com.example.bodyguard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBAi-yovpJsPD2jX7vLdKJEhb5pXNlG3Y',
    appId: '1:1038391091623:ios:384e585d3db478b6c65682',
    messagingSenderId: '1038391091623',
    projectId: 'bodyguard-d274c',
    databaseURL: 'https://bodyguard-d274c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bodyguard-d274c.appspot.com',
    iosBundleId: 'com.example.bodyguard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbRLbQ1eueEZa2vqG1diOfV9PcNt8SR-s',
    appId: '1:1038391091623:web:07c153065f05aad7c65682',
    messagingSenderId: '1038391091623',
    projectId: 'bodyguard-d274c',
    authDomain: 'bodyguard-d274c.firebaseapp.com',
    databaseURL: 'https://bodyguard-d274c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bodyguard-d274c.appspot.com',
    measurementId: 'G-LDM93YV4KT',
  );

}